config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  devise_scope :user do
    get "/auth/:provider/callback" => "callbacks#github"
  end

  authenticated :user do
    root 'repos#index', as: :authenticated_root
  end

  get 'users/auth/github' => "callbacks#github", as: :github
  # resources :issues #Don't need any of the issue routes...
  resources :scans, :only => [:show, :index, :destroy]
  resources :repos, :only => [:index, :show, :new, :create, :destroy]

  get 'issues/publish/:id' => 'issues#publish', as: :publish_issues
  match 'users/settings/' => 'users#settings', as: :user_settings, via: [:get, :post]
  match 'repos/actions' => 'repos#actions', as: :actions, via: [:get, :post]
end

app/models/repo.rb
require "net/http"

class Repo < ActiveRecord::Base
	belongs_to :user
	validates :user_id, presence: true
	validates :html_url, presence: true
	has_many :scans, dependent: :destroy
	has_many :issues, dependent: :destroy


  after_destroy { |record|
    Scan.destroy(record.scans.pluck(:id))
    Issue.destroy(recond.issues.pluck(:id))
  }

	def self.get_repo url, current_user
		# first check url exists
		parsed_url = url.split('/')
		
		# if repo already exists
		if Repo.where(:owner => parsed_url[-2].downcase).where(:name => parsed_url[-1].downcase).where(:user_id => current_user).exists?
			return -1
		end

		full_name = parsed_url[-2] + "/" + parsed_url[-1]
		params = {}
		url = URI.parse("https://api.github.com/repos/" + full_name)
		req = Net::HTTP.new(url.host, url.port)
		req.use_ssl = true
		res = req.request_head(url.path)

		if res.code == "200"
			github = ApplicationHelper.github(current_user)
			if (github == nil)
				return nil
			end
			git_repo = github.repo(full_name)
			params = {
				name: parsed_url[-1].downcase, 
				owner: parsed_url[-2].downcase,
				html_url: git_repo[:html_url],
				description: git_repo[:description],
				language: git_repo[:language],
				size: git_repo[:size],
				user_id: -1
			}
			return params
		end
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :repos, dependent: :destroy
  has_many :scans
  has_many :issues
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:github]
  validates :access_token, length: { is: 40,
    wrong_length: "You entered %{count} characters, access tokens are 40 characters"  }

  after_destroy { |record|
    Repo.destroy(record.repos.pluck(:id))
  }

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/controllers/repos_controller.rb
class ReposController < ApplicationController
  before_action :set_repo, only: [:show, :edit, :update, :destroy]
  include ScansHelper

  # GET /repos
  # GET /repos.json
  def index
  end

  # GET /repos/1
  # GET /repos/1.json
  def show
    final_params = []
    unless @repo.scans.last == nil
      last_scan_id = @repo.scans.last.id
      final_query_array = ["SELECT * FROM issues WHERE scan_id = ?", "ORDER BY issues.severity DESC"]
      final_params.push(last_scan_id)
      final_query = final_query_array.join(" ")
      @issues = Issue.find_by_sql [final_query, *final_params]
    end
  end

  # GET /repos/new
  def new
    @repo = Repo.new
  end

  # GET /repos/1/edit
  def edit
  end

  # POST /repos
  # POST /repos.json
  def create
    url = repo_params[:html_url]
    params = Repo.get_repo(url, current_user)
    if params == nil
      redirect_to :back, notice: 'Error with API access token.'
      return
    end
    if params == -1
      redirect_to :back, alert: 'Repo already exists' and return
    end

    params[:user_id] = current_user.id
    @repo = Repo.new(params)

    respond_to do |format|
      if @repo.save
        format.html { redirect_to @repo, notice: 'Repo was successfully created.' }
        format.json { render :show, status: :created, location: @repo }
      else
        format.html { render :new }
        format.json { render json: @repo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /repos/1
  # PATCH/PUT /repos/1.json
  def update
    respond_to do |format|
      if @repo.update(repo_params)
        format.html { redirect_to @repo, notice: 'Repo was successfully updated.' }
        format.json { render :show, status: :ok, location: @repo }
      else
        format.html { render :edit }
        format.json { render json: @repo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /repos/1
  # DELETE /repos/1.json
  def destroy
    @repo.destroy
    respond_to do |format|
      format.html { redirect_to repos_url, notice: 'Repo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def actions
    repos = Repo.find(params[:repo_ids])
    # Before proceeding, check if github token is valid
    begin
      github = ApplicationHelper.github(current_user)
      if (github == nil)
        redirect_to :back, notice: 'Error with Octokit api access_token.'
        return
      end
    end

    if params[:delete]
      repos.each do |repo|
        repo.destroy
      end
      redirect_to :back, notice: 'Repos were successfully deleted.'
    end

    if params[:scan]
      @scans = []
      repos.each do |repo|
        @scan = ScansHelper.scan(repo, current_user)
        @scans.push(@scan)
      end

      Rails.cache.write("repos", repos)

      redirect_to url_for(:controller => :scans, :action => :index)

      UserNotifier.scan_done_email(current_user, repos).deliver

      #check to see if any errors while scanning
      # respond_to do |format|
      #   if @scan.save
      #     format.html { redirect_to @scan, notice: 'Scans were successfully created.' }
      #     format.json { render :show, status: :created, location: @scan }
      #   else
      #     format.html { render :new }
      #     format.json { render json: @scan.errors, status: :unprocessable_entity }
      #   end
      # end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_repo
      @repo = Repo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def repo_params
      params.require(:repo).permit(:name, :owner, :html_url, :description, :language, :size, :user_id, :repo_ids => [])
    end
end

app/helpers/repos_helper.rb
module ReposHelper
end

app/views/repos/_form.html.erb
<%= bootstrap_form_for(@repo) do |f| %>
  <% if @repo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@repo.errors.count, "error") %> prohibited this repo from being saved:</h2>

      <ul>
      <% @repo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" id="add_repo_field">
    <%= f.url_field :html_url, required: true, label: "Github Url" %>
  </div>

  <div class="actions" id="add_repo_submit">
    <%= f.submit %>
  </div>
<% end %>

app/views/repos/actions.html.erb
<h3> Done </h3>

app/views/repos/edit.html.erb
<h1>Editing Repo</h1>

<%= render 'form' %>

<%= link_to 'Show', @repo %> |
<%= link_to 'Back', repos_path %>

app/views/repos/index.html.erb
<p id="notice"><%= notice %></p>

<%= javascript_tag do %>
	window.onload = function() {
    if(!window.location.hash) {
        window.location = window.location + '#loaded';
        window.location.reload();
    }
	}
<% end %>

<div class="overlay">
    <div id="loading-img"></div>
</div>

<div class="repo-index-page">

	<h1>My Repositories</h1>

	<h4>Select from the following list to scan for dependencies.</h4>

	<% if current_user && ((Repo.where(user_id: current_user.id).size()) > 0) %>
		<table class="table">
			<%= form_tag(actions_path, :method => 'post') do %>
				<% @repos.each do |repo| %>
				<tr>
					<td><%= check_box_tag("repo_ids[]", repo.id) %></td>
					<td><%= repo.owner + "/" + repo.name %></td>
				</tr>
				<% end %>
				<%= submit_tag "Delete", name: 'delete', :class => "btn btn-default", 'data-disable-with' => "Delete" %>
				<%= submit_tag "Scan Selected", name: 'scan', :id => "scan-button", :class => "btn btn-default", 'data-disable-with' => "Scan Selected" %>
			<% end %>
		</table>
	<% else %>
		<p>You currently have no repositories to scan.</p>
	<% end %>

</div>

app/views/repos/new.html.erb
<p id="alert"><%= alert %></p>
<h1>New Repo</h1>

<%= render 'form' %>

<%= link_to 'Back', repos_path %>

app/views/repos/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Project Detail: <%= @repo.name %></h2>


<table class="table table-striped">
    <tbody>
      <tr>
        <th>Name</th>
        <td><%= @repo.name %></td>
      </tr>
      <tr>
        <th>Ower</th>
        <td><%= @repo.owner %></td>
      </tr>
      <tr>
        <th>URL</th>
        <td><%= @repo.html_url %></td>
      </tr>
      <tr>
        <th>Language</th>
        <td><%= @repo.language %></td>
      </tr>
      <tr>
        <th>Size</th>
        <td><%= @repo.size %></td>
      </tr>
      <tr>
        <th>Number of Scans</th>
        <% if @repo.scans %>
          <td><%= @repo.scans.count %></td>
        <% else %>
          <td>0</td>
        <% end %>
      </tr>
      <tr>
        <th>Most Recently Scanned On</th>
        <% if @repo.scans.last %>
          <td><%= @repo.scans.last.created_at %></td>
        <% else %>
          <td>N/A</td>
        <% end %>
      </tr>
      <tr>
        <th>Number of Vulnerabilities</th>
        <% if @repo.scans.last %>
          <td><%= @repo.scans.last.issues.count %></td>
        <% else %>
          <td>N/A</td>
        <% end %>
      </tr>
      <tr>
        <th>Most Severe Issues</th>
        <% if @issues %>
          <td><%= select_tag 'issues', options_for_select(@issues.collect{ |issue| [issue.description] })%></td>
        <% else %>
          <td><%= select_tag 'issues', options_for_select(['N/A']) %></td>
        <% end %>
      </tr>

    </tbody>
</table>