config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  devise_scope :user do
    get "/auth/:provider/callback" => "callbacks#github"
  end

  authenticated :user do
    root 'repos#index', as: :authenticated_root
  end

  get 'users/auth/github' => "callbacks#github", as: :github
  # resources :issues #Don't need any of the issue routes...
  resources :scans, :only => [:show, :index, :destroy]
  resources :repos, :only => [:index, :show, :new, :create, :destroy]

  get 'issues/publish/:id' => 'issues#publish', as: :publish_issues
  match 'users/settings/' => 'users#settings', as: :user_settings, via: [:get, :post]
  match 'repos/actions' => 'repos#actions', as: :actions, via: [:get, :post]
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  belongs_to :scan
  belongs_to :repo
  belongs_to :user
  validates :repo_id, presence: true
  validates :scan_id, presence: true
end

app/controllers/issues_controller.rb
require 'octokit'

class IssuesController < ApplicationController
  before_action :set_issue, only: [:show, :edit, :update, :destroy]

  # GET /issues
  # GET /issues.json
  def index
    @issues = Issue.where(:user_id => current_user.id)
  end

  # GET /issues/1
  # GET /issues/1.json
  def show
  end

  # GET /issues/new
  def new
    @issue = Issue.new
  end

  # GET /issues/1/edit
  def edit
  end

  # POST /issues
  # POST /issues.json
  def create
    @issue = Issue.new(issue_params)

    respond_to do |format|
      if @issue.save
        format.html { redirect_to @issue, notice: 'Issue was successfully created.' }
        format.json { render :show, status: :created, location: @issue }
      else
        format.html { render :new }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /issues/1
  # PATCH/PUT /issues/1.json
  def update
    respond_to do |format|
      if @issue.update(issue_params)
        format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
        format.json { render :show, status: :ok, location: @issue }
      else
        format.html { render :edit }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    @issue.destroy
    respond_to do |format|
      format.html { redirect_to issues_url, notice: 'Issue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def publish
    begin
      github = ApplicationHelper.github(current_user)
      if (github == nil)
       redirect_to :back, notice: 'Error with Octokit api access_token.'
      return
    end
    @issue = Issue.find(params[:id])
    @publish_repo  = Repo.find(@issue.repo_id)
    # check if access token
    if current_user.access_token == "" or current_user.access_token.nil?
      redirect_to :back, notice: 'Need valid GitHub Access Token in User Settings to Publish Issues' and return
    else
      user_github = Octokit::Client.new(:access_token => current_user.access_token)
      @result = user_github.create_issue("#{@publish_repo.owner}/#{@publish_repo.name}", @issue.description, render_to_string("github_issue"))
      redirect_to :back, notice: 'Issue Created' and return
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_issue
      @issue = Issue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def issue_params
      params.require(:issue).permit(:severity, :source, :description, :detail, :fingerprint, :scan_id, :user_id)
    end
end

app/helpers/issues_helper.rb
module IssuesHelper
	def class_for_severity(severity)
		color_map = {
			0 => 'info', 
			1 => 'info',
			2 => 'warning',
			3 => 'warning',
			4 => 'warning',
			5 => 'danger',
			6 => 'danger',
			7 => 'danger'
		}
		return color_map[severity]
	end
end

app/views/issues/_form.html.erb
<%= form_for(@issue) do |f| %>
  <% if @issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

      <ul>
      <% @issue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :severity %><br>
    <%= f.number_field :severity %>
  </div>
  <div class="field">
    <%= f.label :source %><br>
    <%= f.text_field :source %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :detail %><br>
    <%= f.text_area :detail %>
  </div>
  <div class="field">
    <%= f.label :fingerprint %><br>
    <%= f.text_field :fingerprint %>
  </div>
  <div class="field">
    <%= f.label :scan_id %><br>
    <%= f.text_field :scan_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/issues/edit.html.erb
<h1>Editing Issue</h1>

<%= render 'form' %>

<%= link_to 'Show', @issue %> |
<%= link_to 'Back', issues_path %>

app/views/issues/github_issue.erb
Detective-V identified the following vulnerability in <%= @publish_repo.name %>:

**Description:** <%= @issue.description %>
**Severity:** &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= @issue.severity %>
**Details:** &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= raw(@issue.detail) %>
**Scanner:** &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= @issue.scanner %>
**File:** &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[<%= @issue.file %>]<% unless @issue.line.nil? %>, **Line:** <%= @issue.line %><% end %>
<% unless @issue.code.nil? %>
**Code:**

```
<%= raw(@issue.code) %>
```
<% end %>

app/views/issues/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Issues</h1>

<table>
  <thead>
    <tr>
      <th>Severity</th>
      <th>Source</th>
      <th>Description</th>
      <th>Detail</th>
      <th>Fingerprint</th>
      <th>Repo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @issues.each do |issue| %>
      <tr>
        <td><%= issue.severity %></td>
        <td><%= issue.source %></td>
        <td><%= issue.description %></td>
        <td><%= issue.detail %></td>
        <td><%= issue.fingerprint %></td>
        <td><%= link_to 'Show', issue %></td>
        <td><%= link_to 'Edit', edit_issue_path(issue) %></td>
        <td><%= link_to 'Destroy', issue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Issue', new_issue_path %>

app/views/issues/new.html.erb
<h1>New Issue</h1>

<%= render 'form' %>

<%= link_to 'Back', issues_path %>

app/views/issues/publish.html.erb
<h2> Issue Created </h2>
<h4> <%= @result %> </h4>

app/views/issues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Severity:</strong>
  <%= @issue.severity %>
</p>

<p>
  <strong>Source:</strong>
  <%= @issue.source %>
</p>

<p>
  <strong>Description:</strong>
  <%= @issue.description %>
</p>

<p>
  <strong>Detail:</strong>
  <%= @issue.detail %>
</p>

<p>
  <strong>Fingerprint:</strong>
  <%= @issue.fingerprint %>
</p>

<p>
  <strong>Scan:</strong>
  <%= @issue.scan %>
</p>

<%= link_to 'Edit', edit_issue_path(@issue) %> |
<%= link_to 'Back', issues_path %>