config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  devise_scope :user do
    get "/auth/:provider/callback" => "callbacks#github"
  end

  authenticated :user do
    root 'repos#index', as: :authenticated_root
  end

  get 'users/auth/github' => "callbacks#github", as: :github
  # resources :issues #Don't need any of the issue routes...
  resources :scans, :only => [:show, :index, :destroy]
  resources :repos, :only => [:index, :show, :new, :create, :destroy]

  get 'issues/publish/:id' => 'issues#publish', as: :publish_issues
  match 'users/settings/' => 'users#settings', as: :user_settings, via: [:get, :post]
  match 'repos/actions' => 'repos#actions', as: :actions, via: [:get, :post]
end

app/models/scan.rb
class Scan < ActiveRecord::Base
  belongs_to :repo
  belongs_to :user
  has_many :issues, dependent: :destroy
  validates :repo_id, presence: true
end

app/controllers/scans_controller.rb
class ScansController < ApplicationController
  before_action :set_scan, only: [:show, :edit, :update, :destroy]

  # GET /scans
  # GET /scans.json
  def index
    # @scans = Scan.where(:user_id => current_user.id)
    @srepos = Rails.cache.read("repos")
  end

  # GET /scans/1
  # GET /scans/1.json
  def show
    @issues = @scan.issues.order(severity: :desc)
  end

  # GET /scans/new
  def new
    @scan = Scan.new
  end

  # GET /scans/1/edit
  def edit
  end

  # POST /scans
  # POST /scans.json
  def create
    repo = Repo.find(scan_params[:repo_id])
    @scan = ScansHelper.scan(repo, current_user)

    respond_to do |format|
      if @scan.save
        format.html { redirect_to @scan, notice: 'Scan was successfully created.' }
        format.json { render :show, status: :created, location: @scan }
      else
        format.html { render :new }
        format.json { render json: @scan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scans/1
  # PATCH/PUT /scans/1.json
  def update
    respond_to do |format|
      if @scan.update(scan_params)
        format.html { redirect_to @scan, notice: 'Scan was successfully updated.' }
        format.json { render :show, status: :ok, location: @scan }
      else
        format.html { render :edit }
        format.json { render json: @scan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scans/1
  # DELETE /scans/1.json
  def destroy
    @scan.destroy
    respond_to do |format|
      format.html { redirect_to scans_url, notice: 'Scan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def show_issues

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scan
      @scan = Scan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scan_params
      params.require(:scan).permit(:status, :user_id, :repo_id)
    end
end

app/helpers/scans_helper.rb
module ScansHelper

	def self.scan repo, user

	  tasks = []
	  lang = repo.language
	  status = "No known vulnerabilities"

    @scan = Scan.create(
      repo_id: repo.id,
      status: status,
      user_id: user.id
    )

    if lang != nil
      tasks = Settings.pipeline.tasks_for[lang].split(",")
    end

    logfile = File.open(Rails.root.join("log/scans"), 'a')
    logfile.sync = true

    ApplicationHelper.inside_github_archive(repo, user) do |dir|
      pipeline_options = {
        :appname => repo.name,
        :target => "#{dir}",
        :quiet => false,
        :npm_registry => Settings.pipeline['npm_registry'],
        :run_tasks => tasks,
        :pmd_path => Settings.pipeline['pmd_path'],
        :findsecbugs_path => Settings.pipeline['findsecbugs_path'],
        :logfile => logfile,
        :debug => true
      }

      tracker = Pipeline.run(pipeline_options)
      findings = tracker.findings

      findings.each do |finding|
        @scan.update_attribute(:status, "Vulnerabilities found")
        Issue.create(
          severity: finding.severity,
          source: finding.source,
          description: finding.description,
          detail: finding.detail,
          fingerprint: finding.fingerprint,
          scan_id: @scan.id,
          repo_id: repo.id,
          scanner: finding.source[:scanner],
          file: finding.source[:file], 
          line: finding.source[:line],
          code: finding.source[:code],
          user_id: user.id
        )
      end
	  end

    return @scan
  end
end

app/views/scans/_form.html.erb
<%= form_for(@scan) do |f| %>
  <% if @scan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@scan.errors.count, "error") %> prohibited this scan from being saved:</h2>

      <ul>
      <% @scan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<!--   <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div> -->
  <div class="field">
    <%= f.label :Repo %><br>
    <%= f.collection_select :repo_id, current_user.repos, :id, :name, {class: "form-group"} %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scans/_issues.html.erb
<div class="modal fade" id="issues_modal_<%= index %>" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Issue Details</h4>
      </div>
      <div class="modal-body">
        <p class="row">
          <strong class="col-md-2">Severity</strong>
          <span class="col-md-10"><%= issue.severity %></span>
        </p>

        <p class="row">
          <strong class="col-md-2">Description</strong>
          <span class="col-md-10"><%= issue.description %></span>
        </p>

        <p class="row">
          <strong class="col-md-2">Detail</strong>
          <span class="col-md-10"><%= issue.detail %></span>
        </p class="row">

        <p class="row">
          <strong class="col-md-2">File</strong>
          <span class="col-md-10"><%= issue.file %></span>
        </p>

        <p class="row">
          <strong class="col-md-2">Line</strong>
          <span class="col-md-10"><%= issue.line %></span>
        </p>

        <% if issue.code != ""%>
          <p class="row">
            <strong class="col-md-2">Code</strong>
            <span class="col-md-10"><code><%= issue.code %></code></span>
          </p>
        <% end %>

        <p class="row">
          <strong class="col-md-2">Created At</strong>
          <span class="col-md-10"><%= issue.scan.created_at.strftime("%m/%d/%Y - %H:%M") %></span>
        </p>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= link_to publish_issues_path(:id => issue.id) do %>
          <button class="btn btn-primary">Publish</button>
        <% end %>
    </div>
  </div>
</div>

app/views/scans/edit.html.erb
<h1>Editing Scan</h1>

<%= render 'form' %>

<%= link_to 'Show', @scan %> |
<%= link_to 'Back', scans_path %>

app/views/scans/index.html.erb
<p id="notice"><%= notice %></p>
<div class="scan-result-page">
  <h1>Scans Completed</h1>
  <% if current_user && ((Scan.where(user_id: current_user.id).size()) > 0) %>
    <h4>Number of Repositories Scanned: <%= @srepos.count %></h4>
    <table class="table">
      <thead>
        <tr>
          <th>Repo</th>
          <th>Status</th>
          <th>Number of Vulnerabilities</th>
          <th>Detail</th>
        </tr>
      </thead>
      <tbody>
        <% @srepos.each do |repo| %>
          <tr>
            <td><%= repo.owner %>/<%= repo.name %></td>
            <td><%= repo.scans.last.status %></td>
            <td><%= repo.scans.last.issues.count %></td>
            <td><%= link_to "report", repo.scans.last %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p>No scans created yet.</p>
  <% end %>
</div>

app/views/scans/new.html.erb
<h1>New Scan</h1>
<% if current_user %>
	<%= render 'form' %>
<% else %>
	<p>Please login to access scan page </p>
<% end %>

<%= link_to 'Back', scans_path %>

app/views/scans/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Repo:</strong>
  <%= @scan.repo.owner + "/" + @scan.repo.name %>
</p>

<p>
  <strong>Status:</strong>
  <%= @scan.status %>
</p>

<%= button_to "Delete", {:controller => :scans, :action => 'destroy', :id => @scan.id }, :method => :delete, class: "btn btn-default"%>

<table class="table">
	<thead>
	  <tr>
	    <th>Severity</th>
	    <th>Vulnerabilities Found</th>
	    <th>Detail</th>
	  </tr>
	</thead>
	<tbody>
		<% @issues.each_with_index do |issue, index| %>
		  <tr class="<%= class_for_severity(issue.severity)%>" data-toggle="modal" data-target="#issues_modal_<%= index %>">
		    <td><%= issue.severity %></td>
		    <td><%= issue.description %></td>
<td>View</td>
		    

        <%= render :partial => "issues", :locals => { :issue => issue, :index => index }  %>

		  </tr>
		<% end %>
	</tbody>
</table>