config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  devise_scope :user do
    get "/auth/:provider/callback" => "callbacks#github"
  end

  authenticated :user do
    root 'repos#index', as: :authenticated_root
  end

  get 'users/auth/github' => "callbacks#github", as: :github
  # resources :issues #Don't need any of the issue routes...
  resources :scans, :only => [:show, :index, :destroy]
  resources :repos, :only => [:index, :show, :new, :create, :destroy]

  get 'issues/publish/:id' => 'issues#publish', as: :publish_issues
  match 'users/settings/' => 'users#settings', as: :user_settings, via: [:get, :post]
  match 'repos/actions' => 'repos#actions', as: :actions, via: [:get, :post]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DetectiveV</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<!-- Top Nav Bar -->
	<nav class="navbar navbar-default navbar-fixed-top top-nav">
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <%= image_tag("detectiveVlogo.png", :alt => "logo", :class => "logo navbar-brand") %><a class="navbar-brand" href="/">Detective V</a>
	      <!-- <a class="navbar-brand" href="#">
	        <img alt="Brand" src="...">
	      </a> -->
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav navbar-right">
	      	<% if user_signed_in? %>
	      		<li><%= link_to "Signed in as #{current_user.name}", user_settings_path %></li>
	      		</li>
	      		<li id="signout"><%= link_to "Signout", destroy_user_session_path, method: :delete %>
	      		</li>
	      	<% else %>
						<li id="oauth"><%= link_to "Sign in with Github", user_github_omniauth_authorize_path %></li>
					<% end %>
	      </ul>
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>



	<!-- Side Nav Bar -->
	<div class="row side-bar">
    <div class="side-menu side-nav">
	    <nav class="navbar navbar-default" role="navigation">
		    <!-- Brand and toggle get grouped for better mobile display -->
		    <div class="navbar-header">
	        <div class="brand-wrapper">
            <!-- Brand -->
            <div class="brand-name-wrapper">
              <a class="navbar-brand" href="/repos">
              	<% if !current_user %>Sample<% end %> Repositories
              </a>
            </div>

						<!-- New Project -->
						<% if current_user %>
            	<%= link_to '<i class="glyphicon glyphicon-plus"></i>'.html_safe, new_repo_path, id: 'repo-add-trigger' %>
            <% end %>
	        </div>
		    </div>

		    <!-- Repo List -->
		    <div class="side-menu-container">
		      <ul class="nav navbar-nav side-nav-list">
						<% @repos.each do |repo| %>
							<li class="panel panel-default" id="dropdown">
								<!-- <span class="glyphicon glyphicon-sunglasses"></span><%= repo.name %> -->
								<div>
									<!-- <span class="glyphicon glyphicon-sunglasses"></span><%= repo.name %> -->
									</span><%= link_to repo.owner + "/" + repo.name, repo, {:class => "nav-repo"} %>
									<span class="side-nav-arrow" data-toggle="collapse" href="#dropdown-<%=repo.id%>">
										Scans<span class="caret"></span>
									</span>
								</div>
								<!-- Dropdown level 1 -->
	                <div id="dropdown-<%=repo.id%>" class="panel-collapse collapse">
                    <div class="panel-body">
                        <ul class="nav navbar-nav">
													<% repo.scans.reverse.each do |scan| %>
														<li><%= link_to scan.created_at.strftime("%m/%d/%Y - %H:%M"), scan %></li>
													<% end %>
                        </ul>
                    </div>
	                </div>
								</li>
					    <% end %>
		        </ul>
		    </div><!-- /.navbar-collapse -->

			</nav>
    </div>
	</div>


	<div class="side-body">
		<%= render 'shared/error_messages' %>
		<%= yield %>
	</div>

</body>
</html>